name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - synchronize

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install rust-toolchain with rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        components: rustfmt

    - name: cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build (denying warnings)
      run: RUSTFLAGS='-D warnings' cargo build --all-targets --all-features --verbose
    - name: Run tests
      run: cargo test --verbose
